name: CI/CD to ECS

on:
  push:
    branches: [ "master" ]   # Run only when pushing to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:   # Keep non-sensitive values here
      ECR_REPOSITORY: folarin-devops-practice   # your repo name in ECR
      AWS_REGION: us-east-1                     # your AWS region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

          echo "Building and pushing image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy ECS Service
        run: |
          aws ecs update-service \
             --cluster folarin-devops-cluster \
            --service folarin-devops-task-service-mo19o74h \
            --force-new-deployment
